//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YahtzeeTDD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YahtzeeTDD.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Aces{0,11}│{2,5}.
        /// </summary>
        public static string Aces {
            get {
                return ResourceManager.GetString("Aces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,4} Bonus{0,10}│{1,5}.
        /// </summary>
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Chance{0,9}│{2,5}.
        /// </summary>
        public static string Chance {
            get {
                return ResourceManager.GetString("Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands:.
        /// </summary>
        public static string CommandsHeader {
            get {
                return ResourceManager.GetString("CommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current roll: {0}.
        /// </summary>
        public static string CurrentRoll {
            get {
                return ResourceManager.GetString("CurrentRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice: .
        /// </summary>
        public static string Dice {
            get {
                return ResourceManager.GetString("Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice tried to save an invalid number..
        /// </summary>
        public static string DiceNumberOutOfRange {
            get {
                return ResourceManager.GetString("DiceNumberOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over! Nicely done! Play again?.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Fives{0,10}│{2,5}.
        /// </summary>
        public static string Fives {
            get {
                return ResourceManager.GetString("Fives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,4} Four of a Kind │{1,5}.
        /// </summary>
        public static string FoaK {
            get {
                return ResourceManager.GetString("FoaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Fours{0,10}│{2,5}.
        /// </summary>
        public static string Fours {
            get {
                return ResourceManager.GetString("Fours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Full House{0,5}│{2,5}.
        /// </summary>
        public static string FullHouse {
            get {
                return ResourceManager.GetString("FullHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,4} Large Straight │{1,5}.
        /// </summary>
        public static string LargeStraight {
            get {
                return ResourceManager.GetString("LargeStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╚═══════════════════════════╝.
        /// </summary>
        public static string LogoBottom {
            get {
                return ResourceManager.GetString("LogoBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╠═══════ TDD Yahtzee ═══════╣.
        /// </summary>
        public static string LogoText {
            get {
                return ResourceManager.GetString("LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═══════════════════════════╗.
        /// </summary>
        public static string LogoTop {
            get {
                return ResourceManager.GetString("LogoTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} One Pair{0,7}│{2,5}.
        /// </summary>
        public static string OnePair {
            get {
                return ResourceManager.GetString("OnePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [R]oll, [C]heck Score, [H]ide Score, [S]ave Die, [A]dd Score.
        /// </summary>
        public static string PlayingCommands {
            get {
                return ResourceManager.GetString("PlayingCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently playing a game of Yahtzee!.
        /// </summary>
        public static string RollView {
            get {
                return ResourceManager.GetString("RollView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your dice score!.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-4] Save or unsave die.
        /// </summary>
        public static string SaveDieCommands {
            get {
                return ResourceManager.GetString("SaveDieCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save or unsave which die?.
        /// </summary>
        public static string SaveDieView {
            get {
                return ResourceManager.GetString("SaveDieView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1-15] Save score.
        /// </summary>
        public static string SaveScoreCommands {
            get {
                return ResourceManager.GetString("SaveScoreCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,20}│ Score.
        /// </summary>
        public static string ScoreHeader {
            get {
                return ResourceManager.GetString("ScoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ────────────────────┼───────.
        /// </summary>
        public static string ScoreLine {
            get {
                return ResourceManager.GetString("ScoreLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Sixes{0,10}│{2,5}.
        /// </summary>
        public static string Sixes {
            get {
                return ResourceManager.GetString("Sixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,4} Small Straight │{1,5}.
        /// </summary>
        public static string SmallStraight {
            get {
                return ResourceManager.GetString("SmallStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [N]ew Game, [Q]uit.
        /// </summary>
        public static string StandardCommands {
            get {
                return ResourceManager.GetString("StandardCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Let&apos;s play some Yahtzee!.
        /// </summary>
        public static string StartView {
            get {
                return ResourceManager.GetString("StartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Threes{0,9}│{2,5}.
        /// </summary>
        public static string Threes {
            get {
                return ResourceManager.GetString("Threes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,4} Three of a Kind│{1,5}.
        /// </summary>
        public static string ToaK {
            get {
                return ResourceManager.GetString("ToaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,4} Total Score{0,4}│{1,5}.
        /// </summary>
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Two Pair{0,7}│{2,5}.
        /// </summary>
        public static string TwoPair {
            get {
                return ResourceManager.GetString("TwoPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Twos{0,11}│{2,5}.
        /// </summary>
        public static string Twos {
            get {
                return ResourceManager.GetString("Twos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,4} Upper Score{0,4}│{1,5}.
        /// </summary>
        public static string UpperScore {
            get {
                return ResourceManager.GetString("UpperScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,4} Yahtzee{0,8}│{2,5}.
        /// </summary>
        public static string Yahtzee {
            get {
                return ResourceManager.GetString("Yahtzee", resourceCulture);
            }
        }
    }
}
